import prompts from "prompts";
import cohere from "cohere-ai";
import ora from "ora";
import chalk from "chalk";
import yargs from "yargs";

cohere.init("n7xBASe9XW1nlkP6EcXSh6TNXlq6uD2yZfXTT0La"); // This is your trial API key

const questions = [
    {
        type: "text",
        name: "commit",
        message: "Enter a commit message",
    },
];

prompts.override(yargs.argv);
const { commit, ...responses } = await prompts(questions);
console.log({ responses})
const spinner = ora({
    text: "Generating commit message...",
});

spinner.start();

const response = await cohere.generate({
    model: "a42dcfd7-2d89-4ec3-98aa-7d8af30d754f-ft",
    prompt: `Generate five commit message that follows the conventional commit. More info about conventional commits https://www.conventionalcommits.org/en/v1.0.0/
        --
        Incorrect message: updated the changelog to beta.5
        Expected result: docs: update changelog to beta.5
        --
        Incorrect message: Added the amazing button
        Correct message: feat: add the amazing button
        --
        Incorrect message: The endpoint of the list of tickets has been removed.
        Correct message: feat: remove ticket list endpoint
        --
        Incorrect message: The payment system error has been fixed.
        Correct message: fix: payment system error
        --
        Incorrect message: RTL content will now be rendered correctly.
        Correct message: fix: add support for RTL languages.
        --
        Incorrect message: fixed bug on landing page
        Correct message: fix: landing page bug
        --
        Incorrect message: changes to the readme file
        Correct message: docs: update readme file
        --
        Incorrect message: added a new feature
        Correct message: feat: add new feature
        --
        Incorrect message: formating code
        Correct message: style: format code
        --
        Incorrect message: the readeability of the code has been improved
        Correct message: refactor: improve code readability
        --
        Incorrect message: added new tests to the project
        Correct message: test: add new tests
        --
        Incorrect message: Improved the performance of the app
        Correct message: perf: improve app performance
        --
        Incorrect message: A first approach to improve the checkout process
        Correct message: feat: improve checkout process
        --
        Incorrect message: The code has been formatted
        Correct message: style: format code
        --
        Incorrect message: add favicon
        Correct message: feat: add favicon
        --
        Incorrect message: update environment variables
        Correct message: docs: update environment variables
        --
        Incorrect message: The api url has been changed
        Correct message: feat: change api url
        --
        Incorrect message: critical error fix
        Correct message: fix: critical error
        --
        Incorrect message: Carousel improvements and bug fixing
        Correct message: feat: improve carousel and fix bugs
        --
        Incorrect message: Improve the carousel on mobile
        Correct message: feat: improve carousel on mobile
        --
        Incorrect message: The settings has been changed to improve the performance
        Correct message: feat: change settings to improve the performance
        --
        Incorrect message: The problem was generated by the function "foo"
        Correct message: fix: improve function "foo" to fix the bug
        --
        Incorrect message: endpoint to check if user is a publication member
        Correct message: feat: add endpoint to check if user is a publication member
        --
        Incorrect message: feat(api): endpoint to check if user is a publication member
        Correct message: feat(api): add endpoint to check if user is a publication member
        --
        Incorrect message: delete code
        Correct message: refactor: delete code
        --
        Incorrect message: adding more features
        Correct message: feat: add more features
        --
        Incorrect message: additional features
        Correct message: feat: add more features
        --
        Incorrect message: This commit adds a new feature to the search module that allows users to search for records within a specific date range. The date range can be specified using two new fields on the search form a start date and an end date.
        Correct message: feat(search): add support for searching by date range
        --
        Incorrect message: fix: Add authorization for document access
        Correct message: fix: add authorization for document access
        --
        Incorrect message: fix: added authorization for document access
        Correct message: fix: add authorization for document access
        --
        Incorrect message: fix: add authorization for document access.
        Correct message: fix: add authorization for document access
        --
        Incorrect message: add test scenario to check if entering character as mobile number is forbidden
        Correct message: test: add negative test for entering mobile number
        --
        Incorrect message: I've added a delete route to the accounts controller
        Correct message: feat: add delete route to accounts controller
        --
        Incorrect message: implemented automatic login for new verified signups because currently new users have to manually log in after signing up.
        Correct message: implement automatic login for new verified signups because currently new users have to manually log in after signing up.
        --
        Incorrect message: ${commit}
        Correct message: `,
    max_tokens: 42,
    temperature: 0.1,
    k: 0,
    p: 0.75,
    frequency_penalty: 0.9,
    presence_penalty: 0,
    stop_sequences: ["--"],
    num_generations: 5,
    return_likelihoods: "NONE",
});

const cohereResponse = response.body.generations[0].text;
const suggestedCommit = cohereResponse.split("\n")[0];

spinner.stop();

const { isSuggestionAccepted } = prompts({
    type: "confirm",
    name: "suggestion",
    message: `${chalk.green(suggestedCommit)}. Do you want to use this commit message?`,
    initial: true,
});
