blank_issues_enabled: false
contact_links:
  - name: ❓ Question
    url: https://github.com/dartilesm/alexgit/discussions
    about: If you have any questions, doubts or concerns, please do not hesitate to let us know through the discussion section.
