# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  cache-install-and-build:
    name: Build Package
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14, 16, 18]
        
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm run build
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        
      - name: Test
        run: pnpm run test
